{ pkgs, ... }:
{
  # Used to find the project root
  projectRootFile = "flake.nix";

  # Formats *.nix
  programs.nixfmt.enable = true;
  # Formats *.json, etc.
  programs.prettier.enable = true;
  # Formats *.toml
  programs.taplo.enable = true;
  # Checks *.sh and *.bash files.
  programs.shellcheck.enable = true;

  # Files to exclude from formatting.
  settings.global.excludes = [
    ".editorconfig"

    # Binary file
    "*.jpeg"
    "*.png"

    # These are generated by cachix, I feel safer if they aren't touched when
    # formatting.
    "cachix.nix"
    "cachix/**"

    # Misc large files that I don't feel like formatting.
    "keysymdef.h"
    "keysyms.txt"
    "output.xkb"

    # Files which I don't have a formatter for
    "modules/ssh/config"
    "output.xkb"
    "system-modules/kde/metadata.desktop"
  ];
}
